### ISSUE TITLE
Реализовать функцию поиска полос на перекресте

### ISSUE THREAD

**Issue by AndrewGavril** [moevm/mse_indefinite_nav_cv#20]
1. Собрать набор картинок, где бот стоит у красной линии (на перекрестке) или видео
2. Определить как можно обрезать изображение, чтобы детектить разметку на перекрестке
3. Привести примеры детекции фич разметки или пример их отсутсвия

Полоса -- полоса дорожного движения, где должен ехать бот
Необходимо определить точки интереса -- начало этих полос (левая граница начали и правая)

Поиск точек интереса на изображении: SIFT, SURF, ORB

**Comment by alexundertable** [comment]
ORB:
Avg time (2 detections + matching): 6.498 ms
Avg features: 179
Avg matches: 75
![image](https://user-images.githubusercontent.com/18117531/162733999-997f3dab-e94a-41c1-83a8-c96cc2bff47b.png)

SIFT:
Avg time (2 detections + matching): 65.577 ms
Avg features: 222
Avg matches: 132
![image](https://user-images.githubusercontent.com/18117531/162734477-1a7742a6-ed7a-4449-b12a-9586f2955408.png)

SURF:
Ругается, что запатентован. Могу попробовать потом собрать в некоммерческой конфигурации

(пока обрезал просто 1/3 сверху)
