### ISSUE TITLE
Научиться нарисовать линии на перекрестках для lane_following с учетом что мы знаем начало и конец

### ISSUE THREAD

**Issue by light5551** [moevm/mse_indefinite_nav_cv#30]

**Comment by alexundertable** [comment]
Взял 2 нужные точки, третью определил как (p0.x, p1.y), по этим трем точкам сгенерировал и нарисовал квадратичную кривую безье. Это то, что требовалось?
![image](https://user-images.githubusercontent.com/18117531/163869331-662e4120-29b8-4545-b999-ce1f3afb942a.png)

**Comment by AndrewGavril** [comment]
В PR сделать функцию, которая на вход получает изображение, индекс направления поворота и координаты 4 точек
Нужно 3 картинки для данного перекрестка с полной разсетки для каждого из поворотом
